import type { Metadata } from 'next';
import { Sidebar } from '@/components/common/Sidebar';
import { nanumSquare } from './fonts';
import './globals.css';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ko" className={`${nanumSquare.className} h-full antialiased`}>
      <body className="min-h-full p-4">
        {/* TODO: collapsed 상태 제어 추가하기 */}
        <Sidebar />
        <main className="ml-[268px] min-h-[calc(100vh-32px)] min-w-0">{children}</main>
      </body>
    </html>
  );
}
